spring:
  application:
    name: market-app
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/market
    username: postgres
    password: password
    name: market

  sql:
    init:
      mode: embedded
      schema-locations: classpath:schema.sql

logging:
  level:
    yandex.workshop.market: DEBUG
    io.r2dbc: DEBUG
    org.springframework.r2dbc: DEBUG

server:
  port: 8080

#  liquibase:
#    change-log: classpath:db/changelog/db.changelog-master.yaml
#    default-schema: public
#    enabled: true
